### ISSUE TITLE
keyerror items when adding memories

### ISSUE THREAD

**Issue by chris-aeviator** [QuangBK/generativeAgent_LLM#5]
![grafik](https://github.com/QuangBK/generativeAgent_LLM/assets/11522213/1f9f2296-9612-4817-9566-bf9cc7865d28)

```
### Instruction:
{{recent_memories}}

### Input:
Given only the information above, what are 3 most salient high-level questions we can answer about the subjects in the statements?

### Response:
{{#geneach 'items' num_iterations=3}}{{gen 'this' top_k=30 top_p=0.18 repetition_penalty=1.15 temperature=1.99 stop='
'}}
{{/geneach}}

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <cell line: 6>:6                                                                              │
│                                                                                                  │
│ /content/generativeAgent_LLM/server/generativeAgent.py:122 in add_memories                       │
│                                                                                                  │
│   119 │   │                                                                                      │
│   120 │   │   if not self.reflecting and self.aggregate_importance > self.reflection_threshold   │
│   121 │   │   │   self.reflecting = True                                                         │
│ ❱ 122 │   │   │   self._relection()                                                              │
│   123 │   │   │   self.aggregate_importance = 0.0                                                │
│   124 │   │   │   self.reflecting = False                                                        │
│   125                                                                                            │
│                                                                                                  │
│ /content/generativeAgent_LLM/server/generativeAgent.py:144 in _relection                         │
│                                                                                                  │
│   141 │   │   return result['items']                                                             │
│   142 │                                                                                          │
│   143 │   def _relection(self,):                                                                 │
│ ❱ 144 │   │   list_salient = self._get_salient()                                                 │
│   145 │   │   list_docs = []                                                                     │
│   146 │   │   for salient_temp in list_salient:                                                  │
│   147 │   │   │   docs = self.retriever.get_relevant_documents(salient_temp, self.get_current_   │
│                                                                                                  │
│ /content/generativeAgent_LLM/server/generativeAgent.py:134 in _get_salient                       │
│                                                                                                  │
│   131 │   │                                                                                      │
│   132 │   │   prompt = self.guidance(PROMPT_SALIENT, silent=self.silent)                         │
│   133 │   │   result = prompt(recent_memories=recent_memories_text)                              │
│ ❱ 134 │   │   return result['items']                                                             │
│   135 │                                                                                          │
│   136 │   def _get_insights(self, list_docs):                                                    │
│   137 │   │   docs = list_docs                                                                   │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/guidance/_program.py:470 in __getitem__                  │
│                                                                                                  │
│   467 │   │   │   self._execute_complete.set()                                                   │
│   468 │                                                                                          │
│   469 │   def __getitem__(self, key):                                                            │
│ ❱ 470 │   │   return self._variables[key]                                                        │
│   471 │                                                                                          │
│   472 │   def __contains__(self, key):                                                           │
│   473 │   │   return key in self._variables                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
KeyError: 'items'


```

result is actually this string

```
### Instruction:
{{recent_memories}}

### Input:
Given only the information above, what are 3 most salient high-level questions we can answer about the subjects in the statements?

### Response:
{{#geneach 'items' num_iterations=3}}{{gen 'this' top_k=30 top_p=0.18 repetition_penalty=1.15 temperature=1.99 stop='
'}}
{{/geneach}}
```

### update
adding a single memory seems to work

**Comment by QuangBK** [comment]
I'm not sure why this happens but adding memories makes it work, I think the `recent_memories` is empty in this case. Also, make sure using the `guidance==0.0.63` for stability.

**Comment by chris-aeviator** [comment]
I can confirm beeing able to add mem one by one, but run into the same issue when trying to do an myagent.updateStatus() . recent_memories is not empty
    
    sam.retriever.memory_stream[-20:] 
    
    [Document(page_content='Sam is a Ph.D student, his major is CS', metadata={'importance': 7, 'created_at': datetime.datetime(2023, 7, 20, 7, 25, 16, 628631), 'last_accessed_at': datetime.datetime(2023, 7, 20, 7, 25, 16, 628631), 'buffer_idx': 0}),
     Document(page_content='Sam likes computer', metadata={'importance': 1, 'created_at': datetime.datetime(2023, 7, 20, 7, 25, 16, 628631), 'last_accessed_at': datetime.datetime(2023, 7, 20, 7, 25, 16, 628631), 'buffer_idx': 1}),
     Document(page_content='Sam lives with his friend, Bob', metadata={'importance': 1, 'created_at': datetime.datetime(2023, 7, 20, 7, 25, 16, 628631), 'last_accessed_at': datetime.datetime(2023, 7, 20, 7, 25, 16, 628631), 'buffer_idx': 2}),
     Document(page_content="Sam's farther is a doctor", metadata={'importance': 1, 'created_at': datetime.datetime(2023, 7, 20, 7, 25, 16, 628631), 'last_accessed_at': datetime.datetime(2023, 7, 20, 7, 25, 16, 628631), 'buffer_idx': 3}),
     Document(page_content='Sam has a dog, named Max', metadata={'importance': 1, 'created_at': datetime.datetime(2023, 7, 20, 7, 25, 16, 628631), 'last_accessed_at': datetime.datetime(2023, 7, 20, 7, 25, 16, 628631), 'buffer_idx': 4}),
     Document(page_content='Wants to get his AI company to be successful.', metadata={'importance': 8, 'created_at': datetime.datetime(2023, 7, 20, 7, 25, 16, 628631), 'last_accessed_at': datetime.datetime(2023, 7, 20, 7, 25, 16, 628631), 'buffer_idx': 5}),
     Document(page_content='Sam wake up in the morning', metadata={'importance': 1, 'created_at': datetime.datetime(2023, 7, 20, 7, 25, 16, 628631), 'last_accessed_at': datetime.datetime(2023, 7, 20, 7, 25, 16, 628631), 'buffer_idx': 6}),
     Document(page_content='Sam really wants to get to work to get the marketing project for his AI company done', metadata={'importance': 3, 'created_at': datetime.datetime(2023, 7, 20, 7, 25, 16, 628631), 'last_accessed_at': datetime.datetime(2023, 7, 20, 7, 25, 16, 628631), 'buffer_idx': 7})]
    

  print(sam.update_status())
  
  ### Instruction:
  
  Example for plan:
  Here is {{name}}'s plan from now at 7:14:
  [From 7:14 to 7:45]: Wake up and complete the morining routine
  [From 7:45 to 8:35]: Eat breakfirst
  [From 8:35 to 17:10]: Go to school and study
  [From 17:10 to 22:30]: Play CSGO
  [From 22:30 to 7:30]: Go to sleep
  
  ### Input:
  Today is {{current_time}}. Please make a plan today for {{name}} in broad strokes. Given the summary:
  {{summary}}
  
  ### Response:
  Here is {{name}}'s plan from now at {{current_time}}:
  [From {{now}} to {{gen 'to' pattern='[0-9]+:[0-9][0-9]' stop=']'}}]: {{gen 'task' top_k=30 top_p=0.18 repetition_penalty=1.15 temperature=1.99 stop='
  '}}
  {{#geneach 'items' num_iterations=3}}[From {{gen 'this.from' pattern='[0-9]+:[0-9][0-9]' stop=' '}} to {{gen 'this.to' pattern='[0-9]+:[0-9][0-9]' stop=']'}}]: {{gen 'this.task' top_k=30 top_p=0.18 repetition_penalty=1.15 temperature=1.99 stop='
  '}}

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <cell line: 2>:6                                                                              │
│                                                                                                  │
│ /content/generativeAgent_LLM/server/generativeAgent.py:99 in update_status                       │
│                                                                                                  │
│    96 │   │   │   │   need_replan = False                                                        │
│    97 │   │   │   │   break                                                                      │
│    98 │   │   if need_replan:                                                                    │
│ ❱  99 │   │   │   new_plan = self.make_plan()                                                    │
│   100 │   │   │   self.status = new_plan[0]                                                      │
│   101 │   │   return self.status                                                                 │
│   102                                                                                            │
│                                                                                                  │
│ /content/generativeAgent_LLM/server/generativeAgent.py:204 in make_plan                          │
│                                                                                                  │
│   201 │   │   │   │   │      )                                                                   │
│   202 │   │                                                                                      │
│   203 │   │   current_date = self.get_current_time()                                             │
│ ❱ 204 │   │   list_task = result['items']                                                        │
│   205 │   │   list_task.insert(0, {'from': now, 'to': result['to'], 'task': result['task']})     │
│   206 │   │   list_task_time = []                                                                │
│   207 │   │   for i, task_temp in enumerate(list_task):                                          │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/guidance/_program.py:470 in __getitem__                  │
│                                                                                                  │
│   467 │   │   │   self._execute_complete.set()                                                   │
│   468 │                                                                                          │
│   469 │   def __getitem__(self, key):                                                            │
│ ❱ 470 │   │   return self._variables[key]                                                        │
│   471 │                                                                                          │
│   472 │   def __contains__(self, key):                                                           │
│   473 │   │   return key in self._variables                                                      │
╰─────────────────────────────────────────────────────

**Comment by chris-aeviator** [comment]
sorry for the confusion, I made sure to reinstall guidance 0.63 & it's working now after restarting the kernel :+1:
